steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/bookingfilm-463218/movie-service:$SHORT_SHA',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bookingfilm-463218/movie-service:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud container clusters get-credentials booking-cluster --zone asia-southeast1-a --project bookingfilm-463218
        kubectl set image deployment/movie-deployment movie=gcr.io/bookingfilm-463218/movie-service:$SHORT_SHA -n booking-system

images:
  - gcr.io/bookingfilm-463218/movie-service
options:
  logging: CLOUD_LOGGING_ONLY